package com.securenet.model;


import java.time.Instant;
import java.util.Objects;

/**
 * Immutable value object carrying the MQTT broker credentials issued to an IoT
 * device during onboarding.
 *
 * <p>These credentials allow the device to authenticate with the SecureNet
 * message broker, subscribe to command topics, and publish event topics.
 * They are generated by the
 * { com.securenet.devicemanagement.DeviceManagementService} and must
 * be transmitted to the device over a secure channel.
 *
 * <p><strong>Security note:</strong> the {@code mqttPassword} field is
 * deliberately a one-time value. It should be discarded after delivery; the
 * platform stores only a salted hash.
 */
public record DeviceCredentials(String deviceId, String mqttBrokerUrl, String mqttClientId, String mqttUsername,
                                String mqttPassword, Instant issuedAt, Instant expiresAt) {

    /**
     * @param deviceId      device these credentials belong to
     * @param mqttBrokerUrl fully-qualified broker URL, e.g. {@code mqtts://broker.securenet.io:8883}
     * @param mqttClientId  unique MQTT client identifier for this device
     * @param mqttUsername  MQTT username
     * @param mqttPassword  one-time plaintext MQTT password; store only the hash
     * @param issuedAt      UTC instant at which credentials were generated
     * @param expiresAt     UTC instant after which the credentials are invalid
     */
    public DeviceCredentials(String deviceId, String mqttBrokerUrl, String mqttClientId, String mqttUsername, String mqttPassword, Instant issuedAt, Instant expiresAt) {
        this.deviceId = Objects.requireNonNull(deviceId, "deviceId");
        //this.mqttBrokerUrl = Objects.requireNonNull(mqttBrokerUrl, "mqttBrokerUrl");
        //this.mqttClientId = Objects.requireNonNull(mqttClientId, "mqttClientId");
        //this.mqttUsername = Objects.requireNonNull(mqttUsername, "mqttUsername");
        //this.mqttPassword = Objects.requireNonNull(mqttPassword, "mqttPassword");
        this.mqttBrokerUrl = mqttBrokerUrl;
        this.mqttClientId = mqttClientId;
        this.mqttUsername = mqttUsername;
        this.mqttPassword = mqttPassword;
        this.issuedAt = Objects.requireNonNull(issuedAt, "issuedAt");
        this.expiresAt = Objects.requireNonNull(expiresAt, "expiresAt");
    }

    /**
     * @return device identifier these credentials belong to
     */
    @Override
    public String deviceId() {
        return deviceId;
    }

    /**
     * @return MQTT broker URL
     */
    @Override
    public String mqttBrokerUrl() {
        return mqttBrokerUrl;
    }

    /**
     * @return unique MQTT client identifier
     */
    @Override
    public String mqttClientId() {
        return mqttClientId;
    }

    /**
     * @return MQTT username
     */
    @Override
    public String mqttUsername() {
        return mqttUsername;
    }

    /**
     * @return one-time plaintext MQTT password
     */
    @Override
    public String mqttPassword() {
        return mqttPassword;
    }

    /**
     * @return UTC instant credentials were issued
     */
    @Override
    public Instant issuedAt() {
        return issuedAt;
    }

    /**
     * @return UTC instant after which credentials expire
     */
    @Override
    public Instant expiresAt() {
        return expiresAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DeviceCredentials c)) return false;
        return deviceId.equals(c.deviceId) && issuedAt.equals(c.issuedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(deviceId, issuedAt);
    }
}
